REGISTRY = {
    "student": {
        "directory": "Students",
        "template": "student",
         "effort_areas": ["teaching", "research"],
         "roles": ["advisor", "instructor"],
         "modules": [],
         "type": "entity",
    },
    "project": {
        "directory": "Projects",
        "template": "project",
         "effort_areas": ["research"],
         "roles": [],
         "modules": [],
         "type": "entity",
    },
    "committee": {
        "directory": "Committees",
        "template": "committee",
         "effort_areas": ["service"],
         "roles": ["member"],
         "modules": [],
         "type": "entity",
    },
    "course": {
        "directory": "Courses",
        "template": "course",
         "effort_areas": ["teaching"],
         "roles": ["instructor"],
         "modules": [],
         "type": "entity",
    },
    "module": {
        "directory": "Modules",
        "template": "module",
    },
    "grant": {
        "directory": "Grants",
        "template": "grant",
         "effort_areas": ["research"],
         "roles": ["primary investigator"],
         "modules": [],
         "type": "entity",
    },
    "paper": {
        "directory": "Papers", 
        "template": "paper",
         "effort_areas": ["research"],
         "roles": ["primary investigator"],
         "modules": [],
         "type": "entity",
    },
    "meeting": {
        "directory": "Events/Meetings",
        "template": "meeting",
         "type": "event",
    },
    "offering": {
        "directory": "Offerings",
        "template": "offering",
        "type": "entity",
        "effort_areas": ["teaching"],
        "roles": ["instructor"],
        "modules": [],
    },
    "conference": {
        "directory": "Events/Conferences",
        "template": "conference",
         "type": "event",
    },
    "talk": {
        "directory": "Events/Talks",
        "template": "talk",
        "type": "event",
    },    
    "event": {
        "directory": "Events",
        "template": "event",
        "effort_areas": [],
        "roles": [],
        "modules": [],
    },
    "task": {
        "directory": "Tasks",
        "template": "task",
        "effort_areas": [],
        "roles": [],
        "status": "waiting_for_resources",
        "priority": "normal",
        "modules": [],
},
}
